#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '👷 initial phase  : before committing '

# Check Prettier standards
npm run format ||
(
    echo ' ⚠  Prettier Check Failed. Run npm run format, add changes and try commit again. ⚠ ';
    false;
)
