#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '👷 initial phase  : before committing '

# Check Prettier standards
npm run check-format ||
(
    echo ' ⚠  Prettier Check Failed. Run npm run format, add changes and try commit again. ⚠ ';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '💀 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.  💀'
        false; 
)

# If everything passes... Now we can commit
echo '✅ final phase  : committing. ✅'